// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuKZ2qKcvUR4nqCZ-IX6ynkKB4InftuW8',
    appId: '1:979399699873:web:1733ce5bafbda95e55efe0',
    messagingSenderId: '979399699873',
    projectId: 'fir-concepts-c8079',
    authDomain: 'fir-concepts-c8079.firebaseapp.com',
    storageBucket: 'fir-concepts-c8079.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7HTOO76nnvLOhm2XJWyriKIS1cH_mwoc',
    appId: '1:979399699873:android:60aa35c1bc835fe555efe0',
    messagingSenderId: '979399699873',
    projectId: 'fir-concepts-c8079',
    storageBucket: 'fir-concepts-c8079.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgacQSklNm54r5OfHle6qdlZdTcaTJapQ',
    appId: '1:979399699873:ios:20bf30a7f80c064355efe0',
    messagingSenderId: '979399699873',
    projectId: 'fir-concepts-c8079',
    storageBucket: 'fir-concepts-c8079.appspot.com',
    iosBundleId: 'com.example.pushNotifications',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgacQSklNm54r5OfHle6qdlZdTcaTJapQ',
    appId: '1:979399699873:ios:20bf30a7f80c064355efe0',
    messagingSenderId: '979399699873',
    projectId: 'fir-concepts-c8079',
    storageBucket: 'fir-concepts-c8079.appspot.com',
    iosBundleId: 'com.example.pushNotifications',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuKZ2qKcvUR4nqCZ-IX6ynkKB4InftuW8',
    appId: '1:979399699873:web:b5149eb1867aca2c55efe0',
    messagingSenderId: '979399699873',
    projectId: 'fir-concepts-c8079',
    authDomain: 'fir-concepts-c8079.firebaseapp.com',
    storageBucket: 'fir-concepts-c8079.appspot.com',
  );
}
